import "./globals.css";
import { Assistant } from "next/font/google";
import { ToastContainer } from "react-toastify";

const AssistantFont = Assistant({
	weight: ["400", "500", "600", "700", "800"],
	subsets: ["latin"],
	display: "swap",
});

export const metadata = {
	title: "YT-ecommerce",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={` ${AssistantFont.className} antialiased`}>
				<ToastContainer />
				{children}
			</body>
		</html>
	);
}
